/* Shared activity components, navigation and device-local progress. */
(() => {
  'use strict';
  const C=window.BE_CONTENT, KEY=`be-brilliant:${C.version}`;
  document.title=C.brand+' — '+C.title;
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s??'').normalize('NFKC').replace(/[’‘]/g,"'").toLowerCase().trim().replace(/\s+/g,' ').replace(/\s+([?.!,])/g,'$1');
  const defaults=()=>({version:C.version,answers:{},drafts:{},positions:{},lessons:[],fresh:{},reviews:{},last:'#/home',classroom:false});
  let storageOK=true, state=defaults();
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!x||x.version!==C.version)return;const ids=new Set(C.questions.map(q=>q.id));for(const k of ['answers','drafts','fresh'])if(x[k]&&typeof x[k]==='object'&&!Array.isArray(x[k])){for(const [id,value] of Object.entries(x[k]))if(ids.has(id)){if(k==='answers'){if(value&&typeof value.correct==='boolean'&&typeof value.latestCorrect==='boolean'&&typeof value.answer==='string')state.answers[id]={correct:value.correct,latestCorrect:value.latestCorrect,answer:value.answer,attempts:Math.max(1,Number(value.attempts)||1)};}else if(k==='fresh')state.fresh[id]=value===true;else if(value&&(typeof value.value==='string'||Array.isArray(value.words)))state.drafts[id]={value:typeof value.value==='string'?value.value:'',words:Array.isArray(value.words)?value.words.filter(v=>typeof v==='string'):[]};}}if(x.positions&&typeof x.positions==='object')for(const sec of C.sections){const n=x.positions[sec.id];if(Number.isInteger(n)&&n>=0&&n<sec.count)state.positions[sec.id]=n;}if(Array.isArray(x.lessons))state.lessons=[...new Set(x.lessons.filter(n=>Number.isInteger(n)&&n>=0&&n<C.lessons.length))];if(typeof x.last==='string'&&/^#\//.test(x.last))state.last=x.last;if(x.reviews&&typeof x.reviews==='object')for(const sec of C.sections)if(Array.isArray(x.reviews[sec.id]))state.reviews[sec.id]=x.reviews[sec.id].filter(id=>ids.has(id)&&id.startsWith(sec.id+'-'));state.classroom=x.classroom===true;}catch{storageOK=false;}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}}
  load();
  const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',book:'M3 4h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v15h-6a4 4 0 0 0-3 2 4 4 0 0 0-3-2H3Zm9 2v15',spark:'m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4Z',check:'m5 12 4 4L19 6M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h10',pencil:'m15 4 5 5M4 15 16 3a2 2 0 0 1 5 5L9 20l-6 1Z',blocks:'M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',split:'M7 3v18M17 3v18M3 7l4-4 4 4M13 17l4 4 4-4',picture:'M3 3h18v18H3Zm0 13 6-6 12 11M15 7h.01',chart:'M4 21V11h4v10m3 0V3h4v18m3 0v-7h4v7',arrow:'M4 12h16m-6-6 6 6-6 6',back:'M20 12H4m6-6-6 6 6 6',chevron:'m9 5 7 7-7 7',screen:'M3 4h18v13H3Zm5 17h8m-4-4v4',menu:'M4 6h16M4 12h16M4 18h16',sound:'m11 4-6 5H2v6h3l6 5Zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',refresh:'M3 10a9 9 0 1 1 2 9M3 3v7h7',x:'m6 6 12 12M6 18 18 6',bulb:'M9 18h6m-6 3h6M8 15c0-3-3-3-3-7a7 7 0 1 1 14 0c0 4-3 4-3 7Z',flag:'M5 22V3c5-5 9 5 15 0v11c-6 5-10-5-15 0',done:'m5 12 4 4L19 6',lock:'M6 10V7a6 6 0 0 1 12 0v3M4 10h16v12H4Z',swap:'M3 7h17l-4-4M21 17H4l4 4'};
  const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.spark}"/></svg>`;
  const btn=(label,action,classes='',attrs='')=>`<button class="btn ${classes}" data-action="${action}" ${attrs}>${label}</button>`;
  const link=(label,href,classes='')=>`<a class="${classes}" href="${href}">${label}</a>`;
  const img=(key,classes='',eager=false)=>{const x=C.scenes[key];return `<img class="${classes}" src="${esc(x.src)}" alt="${esc(x.alt)}" width="${key==='hero'?1536:1254}" height="${key==='hero'?1024:1254}" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;};
  const allFor=t=>C.questions.filter(q=>q.type===t);
  const stats=qs=>({completed:qs.filter(q=>state.answers[q.id]).length,correct:qs.filter(q=>state.answers[q.id]?.correct).length,review:qs.filter(q=>state.answers[q.id]&&!state.answers[q.id].correct).length,total:qs.length});
  let route={},lessonUI={},menu=false,dialog=null;
  function parse(){const p=location.hash.replace(/^#\/?/,'').split('/');const view=p[0]||'home';if(view==='learn')return {view,index:Math.max(0,Math.min(7,parseInt(p[1],10)||0))};if(C.sections.some(s=>s.id===view)){const review=p[2]==='review';const list=review?(state.reviews[view]||[]).map(id=>C.questions.find(q=>q.id===id)).filter(Boolean):allFor(view);return{view,index:p[1]==='results'?'results':Math.max(0,Math.min(Math.max(0,list.length-1),parseInt(p[1],10)||0)),review,list};}return{view:['home','activities','progress'].includes(view)?view:'home'};}
  function go(hash){if(location.hash===hash){route=parse();render();}else location.hash=hash;}
  const activityURL=t=>`#/${t}/${state.positions[t]||0}`;
  function navLink(title,href,ic,active){return link(`${icon(ic)}<span>${title}</span>`,href,`nav-link ${active?'active':''}`);}
  function renderShell(content){const s=stats(C.questions);const label=route.view==='home'?'Home':route.view==='learn'?'Learn':route.view==='progress'?'My Progress':route.view==='activities'?'Activities':C.sections.find(x=>x.id===route.view)?.title;document.body.className=`${state.classroom?'classroom':''} ${menu?'menu-open':''}`;$('#app').innerHTML=`<button class="mobile-shade" data-action="menu-close" aria-label="Close menu"></button><aside class="sidebar" aria-label="Main navigation">${link('<span class="brand-mark">b</span><span>Be brilliant.</span>','#/home','brand')}<div class="grade-tag"><span>GRADE 3</span><span>Your English space</span></div><nav class="nav-group">${navLink('Home','#/home','home',route.view==='home')}${navLink('Learn','#/learn/0','book',route.view==='learn')}<p class="nav-label">Let’s practise</p>${C.sections.map(x=>navLink(x.title,activityURL(x.id),x.icon,route.view===x.id)).join('')}<p class="nav-label">Keep growing</p>${navLink('My Progress','#/progress','chart',route.view==='progress')}</nav><div class="sidebar-foot"><div class="mini-progress"><span style="width:${s.completed/90*100}%"></span></div><p><strong>${s.completed} / 90</strong> questions explored</p></div></aside><div class="shell"><header class="topbar">${btn(icon('menu'),'menu','btn-small menu-button','aria-label="Open menu" aria-expanded="'+menu+'"')}<div class="breadcrumb"><span>${esc(C.title)}</span>${icon('chevron')}<strong>${esc(label)}</strong></div><div class="top-actions">${state.classroom?link(`${icon('home')}<span>Home</span>`,'#/home','btn btn-small'):''}${btn(`${icon('screen')}<span>${state.classroom?'Exit Classroom View':'Classroom View'}</span>`,'classroom',`btn-small ${state.classroom?'active':''}`,`aria-pressed="${state.classroom}" aria-label="${state.classroom?'Exit Classroom View':'Classroom View'}"`)}</div></header>${!storageOK?'<div class="storage-warning" role="status">Your browser cannot save progress right now. You can still learn and practise here.</div>':''}<main id="main" class="content" tabindex="-1">${content}<p class="footer-note">A little practice. A little more confidence.</p></main></div>`;if(dialog)showDialog();}
  function heading(eyebrow,title,subtitle='',right=''){return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${right}</div>`;}
  function activityCard(x){const s=stats(allFor(x.id));return link(`<span class="icon-box ${x.color}">${icon(x.icon)}</span><div><h3>${x.title}</h3><p>${x.description}</p><span class="count">${x.count} questions${s.completed?` · ${s.completed} explored`:''}</span></div>${icon('arrow')}`,activityURL(x.id),'activity-card');}
  function home(){const saved=Object.keys(state.answers).length>0||state.lessons.length>0;return `<section class="hero"><div class="hero-copy"><span class="eyebrow">A little English, every day</span><h1>Let’s meet<br><em>${esc(C.title.toLowerCase())}.</em></h1><p>Learn how to use am, is and are.<br>Mia and Leo will show you the way.</p><div class="hero-buttons">${link(`Start Learning ${icon('arrow')}`,'#/learn/0','btn btn-primary')}${link('Choose an Activity','#/activities','btn')}${saved?link('Continue',state.last,'btn btn-quiet'):''}</div></div><div class="hero-art">${img('hero','',true)}<span class="hero-note">Meet Mia & Leo</span></div></section><div class="grammar-strip"><div class="grammar-pair"><span>I</span><b>am</b></div><div class="grammar-pair"><span>He · She · It</span><b>is</b></div><div class="grammar-pair"><span>You · We · They</span><b>are</b></div></div><div class="section-heading"><h2>Your learning path</h2><p>Go at your own pace.</p></div><div class="path-row">${link(`<span class="icon-box teal">${icon('book')}</span><div><h3>First, let’s learn.</h3><p>8 short lessons, lots of little discoveries.</p></div>${icon('arrow')}`,'#/learn/0','path-card')}${link(`<span class="icon-box peach">${icon('spark')}</span><div><h3>Try it together.</h3><p>6 questions with a helping hand.</p></div>${icon('arrow')}`,activityURL('guided'),'path-card')}</div><div class="section-heading"><h2>Put your words to work</h2>${link(`All activities ${icon('arrow')}`,'#/activities','text-link')}</div><div class="activity-grid">${C.sections.filter(x=>x.id!=='guided').map(activityCard).join('')}</div>`;}
  function activities(){return heading('A little practice','What shall we try?','Choose any activity. You can come back to the lessons any time.')+`<div class="activity-grid">${C.sections.map(activityCard).join('')}</div>`;}
  const chip=(text,action,n,selected)=>`<button class="chip ${selected?'selected':''}" data-action="${action}" data-value="${n}" aria-pressed="${!!selected}">${esc(text)}</button>`;
  const hint=text=>`<p class="hint">${icon('bulb')}<span>${text}</span></p>`;
  function lesson(){const l=C.lessons[route.index],u=lessonUI;let body='';const steps=C.lessons.map((x,i)=>`${i?'<span class="step-line"></span>':''}<button class="${i===route.index?'current':state.lessons.includes(i)?'done':''}" data-action="lesson-step" data-value="${i}" aria-label="Lesson ${i+1}: ${x.label}" ${i===route.index?'aria-current="step"':''}>${state.lessons.includes(i)&&i!==route.index?icon('done'):i+1}</button>`).join('');
    if(l.id==='about'){const i=u.example||0;body=`<div class="lesson-grid"><div>${hint(l.hint)}<div class="chips">${l.examples.map((x,j)=>chip(x[0],'example',j,i===j)).join('')}</div><div class="example-box"><p class="eyebrow">${l.examples[i][0]}</p><p class="sentence">${l.examples[i][1]}</p></div></div><div class="lesson-visual">${img('happy')}</div></div>`;}
    if(l.id==='match'){const i=u.subject||0,x=C.subjects[i];body=`<div class="lesson-grid"><div>${hint(l.hint)}<div class="chips">${C.subjects.map((s,j)=>chip(s[0],'subject',j,i===j)).join('')}</div><div class="example-box"><p class="sentence">${esc(x[0])} → <span style="color:var(--teal)">${x[1]}</span></p><p>${x[2]}</p></div></div><div class="lesson-visual">${img('park')}</div></div><div class="tip"><strong>One friend or lots of friends?</strong> You can say <strong>you</strong> to one person or more than one person. Always use <strong>are</strong>.</div>`;}
    if(l.id==='positive'){const i=u.positive||0,x=C.positive[i];body=`<div class="formula"><span class="subject-word">Subject</span> + <span class="be-word">am / is / are</span> + <span class="info-word">Information</span></div>${hint(l.hint)}<div class="chips">${C.positive.map((s,j)=>chip(s[0],'positive',j,i===j)).join('')}</div><div class="word-demo"><div class="word-block subject-word"><small>SUBJECT</small>${x[0]}</div><div class="word-block be-word"><small>BE WORD</small>${x[1]}</div><div class="word-block info-word"><small>INFORMATION</small>${x[2]}</div></div><div class="tip">A name can be the subject, too: <strong>Mia is happy.</strong><br>Two people: <strong>Mia and Leo are friends.</strong></div>`;}
    if(l.id==='short'){body=`<div style="margin-top:22px">${hint(l.hint)}</div><div class="short-list">${C.contractions.map((x,i)=>`<button class="short-pair ${u['short'+i]?'selected':''}" data-action="short" data-value="${i}" aria-label="${x[0]} becomes ${x[1]}" aria-pressed="${!!u['short'+i]}"><span>${u['short'+i]?x[1]:x[0]}</span>${icon('swap')}<b>${u['short'+i]?x[0]:x[1]}</b></button>`).join('')}</div><div class="tip"><strong>I am Mia.</strong> and <strong>I’m Mia.</strong> mean the same thing.</div>`;}
    if(l.id==='negative'){body=`<div class="lesson-grid"><div>${hint(l.hint)}<div class="word-demo"><span class="word-block subject-word">She</span><span class="word-block be-word">is</span>${u.negative?'<span class="word-block not-word">not</span>':''}<span class="word-block info-word">happy.</span></div>${btn(u.negative?'Remove not':'Add not','negative','btn-primary','aria-pressed="'+!!u.negative+'"')}<div class="tip">Leo says: <strong>“I am tired. I’m not ready.”</strong></div></div><div class="lesson-visual">${img('tired')}</div></div><table class="negative-table"><thead><tr><th>Long form</th><th>Short form</th><th>Also correct</th></tr></thead><tbody><tr><td>I am not</td><td><strong>I’m not</strong></td><td>—</td></tr><tr><td>He is not</td><td><strong>He isn’t</strong></td><td>He’s not</td></tr><tr><td>They are not</td><td><strong>They aren’t</strong></td><td>They’re not</td></tr></tbody></table><div class="tip">Use <strong>I’m not</strong>. We do not say “I’mn’t”.</div>`;}
    if(l.id==='questions'){const examples=[['She','is','happy'],['They','are','at school'],['I','am','late']],i=u.question||0,x=examples[i];body=`<div class="chips">${examples.map((a,j)=>chip(a.join(' ')+'.','question-example',j,i===j)).join('')}</div>${hint(l.hint)}<div class="question-stage ${u.flipped?'flipped':''}" aria-label="${u.flipped?x[1]+' '+(x[0]==='I'?'I':x[0].toLowerCase())+' '+x[2]+'?':x.join(' ')+'.'}"><span class="word-block subject-word subject-swap">${u.flipped&&x[0]!=='I'?x[0].toLowerCase():x[0]}</span><span class="word-block be-word be-swap">${u.flipped?x[1][0].toUpperCase()+x[1].slice(1):x[1]}</span><span class="word-block info-word">${x[2]}</span><span class="word-block punctuation">${u.flipped?'?':'.'}</span></div>${btn(u.flipped?'Back to a sentence':'Make a question','flip-question','btn-primary','aria-pressed="'+!!u.flipped+'"')}<div class="tip">Start with <strong>Am, Is</strong> or <strong>Are</strong>.<br>We do not use <strong>do</strong> or <strong>does</strong> in these questions.</div>`;}
    if(l.id==='answers'){const ex=[['Are you happy?','Yes, I am.','No, I’m not.','You are answering about yourself: use I.'],['Is she at school?','Yes, she is.','No, she isn’t.','She stays she in the answer.'],['Are they ready?','Yes, they are.','No, they aren’t.','They stays they in the answer.'],['Am I late?','Yes, you are.','No, you aren’t.','Your friend asks about themself. Say you when you answer.']],i=u.answerQuestion||0;body=`<div class="chips">${ex.map((x,j)=>chip(x[0],'answer-question',j,i===j)).join('')}</div><div class="example-box"><p class="sentence">${ex[i][0]}</p><div class="toggle-row">${chip('Yes','answer-yes',1,u.answerYes!==false)}${chip('No','answer-yes',0,u.answerYes===false)}</div><p class="answer-sentence">${ex[i][u.answerYes===false?2:1]}</p><p style="margin-top:13px">${ex[i][3]}</p></div><div class="tip">In a yes answer, keep the full word: <strong>“Yes, I am.”</strong><br>We do not say “Yes, I’m.”</div>`;}
    if(l.id==='recap'){const kinds=['Positive','Negative','Question'],i=u.recap||0;body=`<div class="chips">${kinds.map((x,j)=>chip(x,'recap',j,i===j)).join('')}</div><div class="example-box"><p class="eyebrow">${kinds[i]}</p><p class="sentence">${['They are at school.','They are not at school.','Are they at school?'][i]}</p>${i===2?'<p class="answer-sentence">Yes, they are. / No, they aren’t.</p>':''}</div><div class="grammar-strip"><div class="grammar-pair"><span>I</span><b>am</b></div><div class="grammar-pair"><span>He · She · It</span><b>is</b></div><div class="grammar-pair"><span>You · We · They</span><b>are</b></div></div><div class="tip">A name or one thing → <strong>is</strong><br>Two or more people or things → <strong>are</strong></div>`;}
    return heading('Learn with Mia & Leo','Small steps. Big discoveries.','Explore all eight lessons, in any order.')+`<div class="lesson-steps" aria-label="Lesson steps">${steps}</div><section class="lesson-sheet"><p class="eyebrow">Lesson ${route.index+1} of 8 · ${l.label}</p><h2 class="lesson-title">${l.title}</h2><p class="lesson-summary">${l.summary}</p>${body}</section><div class="lesson-foot">${btn(`${icon('back')} Back`,'lesson-back','',route.index===0?'disabled':'')}${hint(`${state.lessons.length} of 8 lessons explored`)}${btn(`${route.index===7?'Let’s Practise':'Next Lesson'} ${icon('arrow')}`,'lesson-next','btn-primary')}</div>`;
  }
  function current(){return route.list?.[route.index];}
  function draft(q){return state.drafts[q.id]||{value:'',words:[]};}
  function record(q){return state.fresh[q.id]?null:state.answers[q.id];}
  function valid(q,value){return(q.accepted||[q.answer]).some(a=>norm(a)===norm(value));}
  function correction(q){if(q.type==='fill')return q.prompt.replace('___',q.answer);if(q.type==='truefalse')return q.correction;return q.answer;}
  function feedback(q,r){return `<div class="feedback ${r.latestCorrect?'':'retry'}" role="status" aria-live="polite">${icon(r.latestCorrect?'done':'bulb')}<div><strong>${r.latestCorrect?'That’s right!':'Let’s learn from this.'}</strong>${!r.latestCorrect?`<p><b>${q.type==='truefalse'?'Correct sentence':'Answer'}:</b> ${esc(correction(q))}</p>`:''}<p>${esc(q.explanation)}</p>${r.correct&&!r.latestCorrect?'<p>You solved this before. Your progress is still saved.</p>':''}</div></div>`;}
  function options(q,d,r){return `<div class="options ${q.type==='truefalse'?'tf-options':''}" role="group" aria-label="Answer choices">${q.options.map((o,i)=>{const chosen=norm(d.value||r?.answer)===norm(o),correct=norm(o)===norm(q.answer);return `<button class="option ${chosen?'selected':''} ${r&&correct?'correct':''} ${r&&chosen&&!correct?'incorrect':''}" data-action="select" data-value="${esc(o)}" aria-pressed="${chosen}" ${r?'disabled':''}><span class="option-key">${String.fromCharCode(65+i)}</span><span class="option-text">${esc(o)}</span>${r&&correct?`<span class="answer-status">${icon('done')}Correct</span>`:r&&chosen?`<span class="answer-status">${icon('x')}Try again</span>`:''}</button>`;}).join('')}</div>`;}
  function activity(){const sec=C.sections.find(x=>x.id===route.view);if(route.index==='results'||!route.list.length)return results(sec);const q=current(),d=draft(q),r=record(q);let answer='';
    if(q.type==='fill')answer=`<label class="sr-only" for="fill-answer">Missing word or words</label><input id="fill-answer" class="fill-input" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Type or tap a word…" value="${esc(d.value||r?.answer||'')}" ${r?'disabled':''}><div class="word-bank" aria-label="Tap a word">${q.options.map(x=>`<button class="word-token" data-action="fill-word" data-value="${esc(x)}" ${r?'disabled':''}>${esc(x)}</button>`).join('')}</div>`;
    else if(q.type==='build'){const selected=(d.words||[]).filter(id=>q.words.some(w=>w.id===id));answer=`<div class="sentence-tray" aria-label="Your sentence">${selected.length?selected.map(id=>{const w=q.words.find(x=>x.id===id);return `<button class="word-token" data-action="remove-word" data-value="${id}" aria-label="Remove ${esc(w.text)}" ${r?'disabled':''}>${esc(w.text)}</button>`;}).join(''):'<p>Tap the words below to build your sentence.</p>'}</div><div class="build-tools">${btn('Clear','clear','btn-small btn-quiet',!selected.length||r?'disabled':'')}</div><div class="word-bank" aria-label="Available words">${q.words.map(w=>`<button class="word-token" data-action="add-word" data-value="${w.id}" ${selected.includes(w.id)||r?'disabled':''}>${esc(w.text)}</button>`).join('')}</div>`;}
    else answer=options(q,d,r);
    const speak='speechSynthesis' in window?btn(`${icon('sound')}<span>Listen</span>`,'listen','btn-small btn-quiet','aria-label="Listen to the question"'):'';
    let question=`<h2>${esc(q.prompt)}</h2>${q.instruction?`<p class="instruction">${esc(q.instruction)}</p>`:''}${q.type==='build'?'<p class="instruction">Tap a word to add it. Tap it again to put it back.</p>':''}${answer}`;
    if(q.type==='truefalse')question=`<h2>Is the sentence correct?</h2><p class="quote-sentence">“${esc(q.prompt)}”</p>${answer}`;
    if(q.type==='picture')question=`<div class="picture-layout"><div>${img(q.image,'picture-image')}</div><div>${question}</div></div>`;
    const hintBlock=q.hint?`<div class="hint-box">${icon('bulb')} <strong>A little help:</strong> ${esc(q.hint)}</div>`:'';
    const hasAnswer=q.type==='build'?(d.words?.length===q.words.length):!!d.value.trim();
    return heading(route.review?'A little more practice':'Let’s practise',sec.title,sec.description,link(`${icon('blocks')}<span>Activities</span>`,'#/activities','btn btn-small'))+`<div class="question-wrap"><div class="activity-top"><span class="position">${route.review?'Review · ':''}Question ${route.index+1} of ${route.list.length}</span><span class="position">${stats(allFor(sec.id)).correct} correct so far</span></div><div class="progress-track" role="progressbar" aria-label="Questions explored in this activity" aria-valuenow="${stats(allFor(sec.id)).completed}" aria-valuemin="0" aria-valuemax="${sec.count}"><span style="width:${stats(allFor(sec.id)).completed/sec.count*100}%"></span></div><section class="question-card"><div class="question-meta"><span class="pill">${q.form==='mixed'?'Look & think':q.form==='question'?'Questions & answers':q.form+' sentences'}</span>${speak}</div>${question}${hintBlock}${r?feedback(q,r):''}</section><div class="question-foot">${btn(`${icon('back')} Back`,'question-back','',route.index===0?'disabled':'')}<div style="display:flex;gap:10px">${r&&!r.latestCorrect?btn('Try this again','retry-question'):''}${!r?btn(`Check ${icon('check')}`,'check','btn-primary',!hasAnswer?'disabled':''):btn(`${route.index===route.list.length-1?'See Results':'Next'} ${icon('arrow')}`,'question-next','btn-primary')}</div></div>${!r?'<p class="small-note">Take your time. Every answer helps you learn.</p>':''}</div>`;
  }
  function statsBoxes(s){return `<div class="stats-grid"><div class="stat blue"><strong>${s.completed}<span> / ${s.total}</span></strong><span>Completed</span></div><div class="stat green"><strong>${s.correct}</strong><span>Correct</span></div><div class="stat peach"><strong>${s.review}</strong><span>To practise again</span></div></div>`;}
  function results(sec){const s=stats(allFor(sec.id));return `<section class="results"><div class="icon-box teal">${icon('flag')}</div><p class="eyebrow">${sec.title}</p><h1 style="margin-top:12px">${s.correct===s.total?'Look how far you’ve come!':'A little practice goes a long way.'}</h1><p>${s.completed===s.total?'You’ve explored every question in this activity.':'You can come back and explore the remaining questions any time.'}</p>${statsBoxes(s)}<p class="small-note">Your saved progress for this activity.</p><div class="result-actions">${s.review?btn('Review My Mistakes','review','btn-primary',`data-value="${sec.id}"`):''}${btn(`${icon('refresh')}Try Again`,'try-again','',`data-value="${sec.id}"`)}</div>${link(`Choose another activity ${icon('arrow')}`,'#/activities','text-link')}<p class="small-note">Practising again keeps the progress you’ve already made.</p></section>`;}
  function progress(){const s=stats(C.questions);return heading('Every little step counts','My Progress','See what you have explored, and what to try next.')+statsBoxes(s)+`<div class="lesson-progress"><div><h3>Your lessons</h3><p>${state.lessons.length} of 8 lessons explored</p></div>${link('Keep learning','#/learn/0','btn btn-small')}</div><div class="progress-card"><table class="progress-table"><thead><tr><th>Activity</th><th>Completed</th><th>Correct</th><th>Review</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>${C.sections.map(x=>{const n=stats(allFor(x.id));return `<tr><td><strong>${x.title}</strong></td><td class="num">${n.completed} / ${n.total}</td><td class="num">${n.correct}</td><td class="num">${n.review}</td><td>${n.review?btn('Review','review','btn-small',`data-value="${x.id}"`):link(n.completed?'Continue':'Start',activityURL(x.id),'btn btn-small')}</td></tr>`;}).join('')}</tbody></table></div><div class="progress-footer"><p>Progress is saved in this browser on this device. It does not move between devices. Practising a question again does not add extra points.</p>${btn(`${icon('refresh')}Reset Progress`,'reset','btn-small')}</div>`;}
  function render(){let content=route.view==='home'?home():route.view==='activities'?activities():route.view==='learn'?lesson():route.view==='progress'?progress():activity();renderShell(content);adjustSwap();}
  function adjustSwap(){const stage=$('.question-stage');if(stage){const sub=stage.querySelector('.subject-swap'),be=stage.querySelector('.be-swap'),gap=parseFloat(getComputedStyle(stage).gap)||10;stage.style.setProperty('--swap-be',(be.offsetWidth+gap)+'px');stage.style.setProperty('--swap-subject',(sub.offsetWidth+gap)+'px');}}
  function update(){route=parse();menu=false;lessonUI={};if(route.view==='learn'){state.last=`#/learn/${route.index}`;save();}else if(C.sections.some(s=>s.id===route.view)&&route.index!=='results'){if(!route.review)state.positions[route.view]=route.index;state.last=location.hash;save();}render();window.scrollTo(0,0);$('#main')?.focus({preventScroll:true});}
  function check(){const q=current();if(!q||record(q))return;const d=draft(q);let value=d.value;if(q.type==='build'){if(d.words.length!==q.words.length)return;value=d.words.map(id=>q.words.find(w=>w.id===id)?.text||'').join(' ').replace(/\s+([.?])/g,'$1');}if(!value.trim())return;const correct=valid(q,value),old=state.answers[q.id];state.answers[q.id]={correct:correct||!!old?.correct,latestCorrect:correct,answer:value,attempts:(old?.attempts||0)+1};state.fresh[q.id]=false;save();render();$('.feedback')?.scrollIntoView({block:'nearest',behavior:'smooth'});}
  function navigateQuestion(delta){const n=route.index+delta;if(n<0)return;go(`#/${route.view}/${n>=route.list.length?'results':n}${route.review?'/review':''}`);}
  function beginReview(type){const ids=allFor(type).filter(q=>state.answers[q.id]&&!state.answers[q.id].correct).map(q=>q.id);if(!ids.length)return;state.reviews[type]=ids;for(const id of ids){state.fresh[id]=true;delete state.drafts[id];}save();go(`#/${type}/0/review`);}
  function beginAgain(type){for(const q of allFor(type)){state.fresh[q.id]=true;delete state.drafts[q.id];}state.positions[type]=0;save();go(`#/${type}/0`);}
  function showDialog(){const div=document.createElement('div');div.className='modal-backdrop';div.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" aria-describedby="dialog-text"><h2 id="dialog-title">Start fresh?</h2><p id="dialog-text">This will clear all lesson and activity progress saved in this browser. You cannot undo this.</p><div class="modal-actions">${btn('Keep My Progress','cancel-reset','btn-primary')}${btn('Reset Everything','confirm-reset')}</div></section>`;$('#app').append(div);div.querySelector('button').focus();}
  function clearDialog(){dialog=null;$('.modal-backdrop')?.remove();$('[data-action="reset"]')?.focus();}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,v=b.dataset.value,q=current();
    if(a==='menu'){menu=!menu;render();}else if(a==='menu-close'){menu=false;render();}else if(a==='classroom'){state.classroom=!state.classroom;save();render();$('[data-action="classroom"]')?.focus();}
    else if(a==='lesson-step')go(`#/learn/${v}`);
    else if(a==='lesson-back'&&route.index>0)go(`#/learn/${route.index-1}`);
    else if(a==='lesson-next'){if(!state.lessons.includes(route.index))state.lessons.push(route.index);save();go(route.index===7?'#/guided/0':`#/learn/${route.index+1}`);}
    else if(['example','subject','positive','recap'].includes(a)){lessonUI[a]=Number(v);render();$(`[data-action="${a}"][data-value="${v}"]`)?.focus();}
    else if(a==='short'){lessonUI['short'+v]=!lessonUI['short'+v];render();$(`[data-action="short"][data-value="${v}"]`)?.focus();}
    else if(a==='negative'){lessonUI.negative=!lessonUI.negative;render();$('[data-action="negative"]')?.focus();}
    else if(a==='question-example'){lessonUI.question=Number(v);lessonUI.flipped=false;render();$(`[data-action="question-example"][data-value="${v}"]`)?.focus();}
    else if(a==='flip-question'){lessonUI.flipped=!lessonUI.flipped;const stage=$('.question-stage'),x=[['She','is','happy'],['They','are','at school'],['I','am','late']][lessonUI.question||0];stage.querySelector('.subject-swap').textContent=lessonUI.flipped&&x[0]!=='I'?x[0].toLowerCase():x[0];stage.querySelector('.be-swap').textContent=lessonUI.flipped?x[1][0].toUpperCase()+x[1].slice(1):x[1];stage.querySelector('.punctuation').textContent=lessonUI.flipped?'?':'.';adjustSwap();stage.classList.toggle('flipped',lessonUI.flipped);stage.setAttribute('aria-label',lessonUI.flipped?`${x[1]} ${x[0]} ${x[2]}?`:`${x.join(' ')}.`);b.textContent=lessonUI.flipped?'Back to a sentence':'Make a question';b.setAttribute('aria-pressed',lessonUI.flipped);}
    else if(a==='answer-question'){lessonUI.answerQuestion=Number(v);render();$(`[data-action="answer-question"][data-value="${v}"]`)?.focus();}
    else if(a==='answer-yes'){lessonUI.answerYes=v==='1';render();$(`[data-action="answer-yes"][data-value="${v}"]`)?.focus();}
    else if((a==='select'||a==='fill-word')&&q&&!record(q)){state.drafts[q.id]={...draft(q),value:v};save();render();if(a==='select')Array.from(document.querySelectorAll('[data-action="select"]')).find(el=>el.dataset.value===v)?.focus();else $('#fill-answer')?.focus();}
    else if(a==='add-word'&&q&&!record(q)){const d=draft(q);if(q.words.some(w=>w.id===v)&&!d.words.includes(v))state.drafts[q.id]={...d,words:[...d.words,v]};save();render();$(`[data-action="remove-word"][data-value="${v}"]`)?.focus();}
    else if(a==='remove-word'&&q&&!record(q)){const d=draft(q);state.drafts[q.id]={...d,words:d.words.filter(id=>id!==v)};save();render();$(`[data-action="add-word"][data-value="${v}"]`)?.focus();}
    else if(a==='clear'&&q&&!record(q)){state.drafts[q.id]={value:'',words:[]};save();render();$('[data-action="add-word"]')?.focus();}
    else if(a==='check')check();else if(a==='question-back')navigateQuestion(-1);else if(a==='question-next')navigateQuestion(1);
    else if(a==='retry-question'&&q){state.fresh[q.id]=true;delete state.drafts[q.id];save();render();}
    else if(a==='review')beginReview(v);else if(a==='try-again')beginAgain(v);
    else if(a==='reset'){dialog=true;showDialog();}else if(a==='cancel-reset')clearDialog();else if(a==='confirm-reset'){state=defaults();save();dialog=null;go('#/progress');}
    else if(a==='listen'&&q&&'speechSynthesis'in window){try{speechSynthesis.cancel();const t=q.type==='fill'?q.prompt.replace('___','blank'):q.prompt;const u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.85;speechSynthesis.speak(u);}catch{b.textContent='Audio unavailable';}}
  });
  document.addEventListener('input',e=>{if(e.target.id==='fill-answer'){const q=current();if(q){state.drafts[q.id]={...draft(q),value:e.target.value};save();const b=$('[data-action="check"]');if(b)b.disabled=!e.target.value.trim();}}});
  document.addEventListener('keydown',e=>{if(dialog){if(e.key==='Escape'){e.preventDefault();clearDialog();}if(e.key==='Tab'){const buttons=[...document.querySelectorAll('.modal button')],first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.key==='Escape'&&menu){menu=false;render();$('[data-action="menu"]')?.focus();}if(e.key==='Enter'&&e.target.id==='fill-answer'){e.preventDefault();check();}});
  window.addEventListener('hashchange',update);window.addEventListener('resize',adjustSwap);
  route=parse();render();
  // Progressive enhancement: the site works fully when WebMCP is unavailable.
  if(document.modelContext?.registerTool){const life=new AbortController();const registered=[{name:'get_learning_progress',title:'Read learning progress',description:'Read completed, correct and review counts from this browser.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({lessons:state.lessons.length,...stats(C.questions),activities:C.sections.map(s=>({activity:s.id,...stats(allFor(s.id))}))})},{name:'navigate_learning_section',title:'Open a lesson or activity',description:'Navigate to Home, Learn, an activity, or My Progress. Does not answer questions.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['home','learn','activities','progress',...C.sections.map(s=>s.id)]}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const allowed=['home','learn','activities','progress',...C.sections.map(s=>s.id)];if(!input||!allowed.includes(input.section))throw Error('Unknown section.');go('#/'+input.section+(input.section==='learn'?'/0':''));await new Promise(resolve=>setTimeout(resolve,20));return{section:parse().view};}}];for(const tool of registered){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
})();
